window.places = [
    "Caffe Domeva",
    "Pizza Mont d'Or",
    "Le 18",
    "Delecto (Boulangerie culinaire)",
    "Mulan",
    "Mayo-Ketchup",
    "Fenêtre sur Cour",
    "Marmara Sofrasi",
    "Master Cook",
    "Rose Indien",
    "Le Moulin",
    "Milord circus",
    "Lachaume",
    "Accords gourmants",
    "Le Tiroir",
    "Aussie Frenchi",
];
