window.places = [
    "Subway",
    "Pita",
    "Lekker",
    "Kebab",
    "McDo",
    "Sushi Shop",
    "Jap",
    "Aris",
    "la boulange du métro",
    "la boulange Louise Michel",
    "la boulange Niel",
    "la boulange secrète",
    "la boulange en face de Sushi Shop",
    "au Briard",
    "Bagel secret",
    "On a faim !",
    "Trattoria",
    "Bibimbap",
    "Le Lotus Bleu",
    "Damas",
    "le chinois",
    "La petite assiette",
    "Pizzeria Torino",
    "Terra Gourma",
];
