window.places = [
    "Domeva Caffe",
    "Pizza Mont d'Or",
    "Le 18",
    "Delecto (Boulangerie culinaire)",
    "Mulan",
    "Mayo-Ketchup",
    "Fenêtre sur Cour",
    "Marmara Sofrasi",
    "Master Cook",
    "Rose Indien",
    "Le Moulin",
    "Milord circus",
    "Lachaume",
    "Accords gourmands",
    "Le Tiroir",
    "Aussie Frenchi",
    "Racine",
    "Snack Brasil",
    "Happy Bowl",
];
